# Generated by Django 3.2.1 on 2022-07-07 09:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('contact', models.CharField(max_length=150, unique=True)),
                ('balance', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.FloatField()),
                ('time', models.DateTimeField(default=datetime.datetime(2022, 7, 7, 15, 36, 48, 981527))),
                ('status', models.CharField(choices=[('success', 'success'), ('pending', 'pending'), ('aborted', 'aborted')], default='pending', max_length=15)),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_account', to='transaction.account')),
                ('source_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='source_account', to='transaction.account')),
            ],
            options={
                'db_table': 'transfers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('old_balance', models.FloatField()),
                ('amount', models.FloatField()),
                ('new_balance', models.FloatField()),
                ('type', models.CharField(choices=[('debit', 'debit'), ('credit', 'credit')], max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='transaction.account')),
                ('transfer_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_account', to='transaction.account')),
            ],
            options={
                'verbose_name': 'Transaction Historie',
                'db_table': 'histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('deposit', 'deposit'), ('withdrawal', 'withdrawal')], max_length=10)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('success', 'success'), ('pending', 'pending'), ('aborted', 'aborted')], default='pending', max_length=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transaction.account')),
            ],
            options={
                'db_table': 'cash_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['-created_at'], name='accounts_created_645b9a_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['balance'], name='accounts_balance_acc40f_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['-created_at'], name='transfers_created_e9fe28_idx'),
        ),
        migrations.AddIndex(
            model_name='transfer',
            index=models.Index(fields=['amount'], name='transfers_amount_943162_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionhistory',
            index=models.Index(fields=['-created_at'], name='histories_created_ab9882_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionhistory',
            index=models.Index(fields=['type'], name='histories_type_d5639a_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['-created_at'], name='cash_transa_created_8c8b38_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['type'], name='cash_transa_type_0c002a_idx'),
        ),
    ]
