# Generated by Django 3.2.1 on 2022-07-06 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transfer_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('pending', 'pending'), ('aborted', 'aborted')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 17, 44, 36, 467650)),
        ),
    ]
