# Generated by Django 3.2.1 on 2022-07-06 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20220706_1751'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cashtransaction',
            name='depositorwi_created_01df03_idx',
        ),
        migrations.RemoveIndex(
            model_name='cashtransaction',
            name='depositorwi_type_fe7b76_idx',
        ),
        migrations.RemoveField(
            model_name='transactionhistory',
            name='status',
        ),
        migrations.AddField(
            model_name='cashtransaction',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('pending', 'pending'), ('aborted', 'aborted')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('success', 'success'), ('pending', 'pending'), ('aborted', 'aborted')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 6, 18, 35, 48, 233944)),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['-created_at'], name='cash_transa_created_8c8b38_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransaction',
            index=models.Index(fields=['type'], name='cash_transa_type_0c002a_idx'),
        ),
        migrations.AlterModelTable(
            name='cashtransaction',
            table='cash_transaction',
        ),
    ]
